---
title: "CH3-shelter comparison"
author: "Nargol Ghazian"
date: "15/10/2019"
output:
  html_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#open packages 
library(ggplot2)
library(ggthemes)

#import dataset 
main.data <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/Carrizo_shrub_logger.csv")

str(main.data)

#exclude missing values
data.final<-na.omit(main.data)
#check for missing values
head(is.na(data.final))

#getting rid of that extra open factor
data.final$shelter.open <- gsub(" ", "", data.final$shelter.open)
data.final$shelter.open <- as.factor(data.final$shelter.open)
str(data.final)

summary (data.final)
```


```{r}

#Data visualization 
#automatic data 
qplot (data=data.final, temp)#data seem right-skewed
qplot (data=data.final, Intensity)#data looks exponential, but we have to explore more

#let's see if temperature and light intensity are correlated 
qplot(data= data.final, temp, Intensity, geom = c ("point", "smooth")) + xlab("Temperature (°F)") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))#there seems to be a positive correlation

#plot temp and cover.type for different timeblocks
ggplot (data.final, aes(as.factor(cover.type), temp))+ facet_grid(~timeblock) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))


library(ggsignif)

#plot light intensity and cover type for the different shapes
ggplot(data.final, aes(as.factor(cover.type), Intensity, fill= shape)) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))#boxplots overalp, prehaps significanlty different

#plot cover type and temperature for the different shapes
ggplot(data.final, aes(as.factor(cover.type), temp, fill= shape)) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))

#plot change in temperature for the different shapes
ggplot(data.final, aes(as.factor(shape),temp, fill=shape))+geom_boxplot() + facet_grid(~timeblock)+ xlab("Structure")+ ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ theme(axis.text=element_text(size=12))+geom_signif(comparisons = list(c("Triangle", "Square")), 
              map_signif_level=TRUE)
#plot change in light intensity for the different cover types
ggplot(data.final, aes(as.factor(cover.type), Intensity))+ facet_grid(~timeblock) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))

#plot changes in light intensity for the different shapes
ggplot(data.final, aes(as.factor(shape), Intensity, fill=shape))+geom_boxplot() + xlab("Structure")+ ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+theme(axis.title.x=element_blank(),axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ theme(axis.text=element_text(size=12))+geom_signif(comparisons = list(c("Square", "Triangle")), 
              map_signif_level=TRUE)+ theme(legend.position = "none")

#extra plots      
ggplot(data.final, aes(as.factor(shelter.open), temp, fill= as.character(cover.type))) + geom_boxplot() + xlab("Treatment") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+labs (fill= "Cover Type")

#extra plots
ggplot(data.final, aes(as.factor(shelter.open), Intensity, fill= as.character(cover.type))) + geom_boxplot() + xlab("Treatment") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+ labs (fill= "Cover Type")

```


```{r}
#EDA
#explore normality 
#can't do Shapiro-Wilk dataset too large 
library(ggpubr)

ggqqplot(data.final$temp)#data is positively(right) skewed, Gaussian  
hist(data.final$temp) 
ggqqplot(data.final$intensity)#data looks exponential or poisson 
hist(data.final$intensity)
#neither intensity nor temperature follow a normal distribution
```


```{r}
#Models
#explore light and temp relationship
cor.test(data.final$temp, data.final$intensity, method= "kendall")#light and temp are correlated p<0.05


#create scatterplot for the above relationship 
ggplot(data.final, aes(temp, Intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  facet_grid(cover.type~timeblock, scales = "free")+ theme_classic()#prehaps too dense too look at

ggplot(data.final, aes(temp, Intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  facet_grid(~timeblock, scales = "free")+ theme_classic()#prehaps less dense too look at 

ggplot(data.final, aes(temp, Intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm',se= FALSE)+  facet_grid(shape~timeblock, scales = "free")+ theme_classic()

ggplot(data.final, aes(temp, Intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm',se= FALSE)+  facet_wrap(~cover.type, scales = "free")+ theme_classic()

#let's fit some models
lm1 <- glm(temp~as.factor(microsite)* as.factor (cover.type), data = shelter.shrub.open, family="gaussian")
summary (lm1)
library (emmeans)
anova(lm1, test = "Chisq")#all varibles are significant
emmeans(lm1, pairwise~microsite|cover.type)


lm2 <- glm(intensity~as.factor(microsite)* as.factor(cover.type), data = shelter.shrub.open, family="quasipoisson")
summary(lm2) 
anova (lm2, test="Chisq")#all variables are significant
emmeans(lm2, pairwise~microsite|cover.type)


anova1 <- aov (temp~cover.type*timeblock, data.final)
summary (anova1)

anova2 <- aov (Intensity~cover.type*timeblock, data.final)
summary (anova2)

anova3 <-aov (temp~shape*timeblock, data.final)
summary (anova3)

anova4 <-aov (Intensity~shape*timeblock, data.final)
summary (anova4)
```

```{r}
#Summary 



```
```{r}
#explore light and temp relationship
correlation<-cor.test(macro.micro.contrast$temp, macro.micro.contrast$intensity, method= "kendall")
summary(correlation)#light and temp are correlated p<0.05
#kendall's tau=0.281

#create scatterplot for the above relationship 
ggplot(macro.micro.contrast, aes(temp, intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  theme_classic()#Perhaps too dense too look at

ggplot(macro.micro.contrast, aes(temp, intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  facet_grid(~microsite)+ theme_classic()

```






```{r}