---
title: "shrub.open.shelter comparison"
author: "Nargol Ghazian"
date: "04/03/2020"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#GOALS
#1.Describe how to built UPSS.
#2.Exploring UPSS effects on canopy microclimate, including temperature and light intensity, relative to the open and shrub.
#3.Understanding how different light permeabilities and shelter shapes influence the above parameters.

```


```{r}
library (tidyverse)
library(ggplot2)
#import datasets
panoche.climate.2019<-read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/panoche_climate_hourly 2019.csv")

mean.daily.panoche <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/weather station climate.csv")

str(panoche.climate.2019)
na.omit (panoche.climate.2019)#exclude missing values
head(is.na(panoche.climate.2019))#check for missing values
head(na.omit (mean.daily.panoche))
```


```{r}
#DATA VIZ MACRO (WEATHER STATION) 
##macro-climate plots
ggplot (panoche.climate.2019, aes((hour), air.temp)) + geom_smooth() + xlab("Hour (0-24)") + ylab ("Temperature (°C)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#how air temperature changed during 24h period in 2019 during study period

ggplot (panoche.climate.2019, aes((day), air.temp)) + geom_smooth() + xlab("Day") + ylab ("Temperature (°C)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#air temperature over the days of the study period

ggplot (panoche.climate.2019, aes((hour), soil.temp)) + geom_smooth() + xlab("Hour (0-24)") + ylab ("Temperature (°C)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#how soil temperature changed during 24h period in 2019 during study period

ggplot (panoche.climate.2019, aes((day), soil.temp)) + geom_smooth() + xlab("Day") + ylab ("Temperature (°C)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#how soil temperature changed during 24h period in 2019 during study period

ggplot (panoche.climate.2019, aes((hour), radiation)) + geom_smooth() + xlab("Hour (0-24)") + ylab ("Solar Radiation (W/m²)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#how solar radiation changed during 24h period in 2019 during study period

ggplot (panoche.climate.2019, aes((day), radiation)) + geom_smooth() + xlab("Day") + ylab ("Solar Radiation (W/m²)")+  theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))#sunlight experinced over the the study period

library (ggbeeswarm)
ggplot (panoche.climate.2019, aes(as.factor(date), air.temp)) + geom_boxplot() + xlab("Date") + ylab ("Temperature (°C)")+ geom_quasirandom(alpha=0.05)+ theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))+ theme(axis.text.x = element_text(angle = 90))+ geom_smooth(se=FALSE, color="black", aes(group=1))#daily air temperature averages

```

```{r}
#DATA VIZ MICRO
##micro-climate plots
##let's try some plots for shelter, shrub, and open

shelter.shrub.open <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/shrub_contrast_final.csv")#import dataset

ggplot(shelter.shrub.open, aes((microsite), temp, fill=microsite)) + geom_boxplot() + xlab("Microsite") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+theme(axis.text.x = element_text(angle = 90))+theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ labs(fill = "Microsite")+ stat_summary(fun.y=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE)#Boxplot temperaure by microsite

ggplot(shelter.shrub.open, aes((microsite), intensity, fill=microsite)) + geom_boxplot() + xlab("Microsite") + ylab ("Solar Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+theme(axis.text.x = element_text(angle = 90))+theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ labs(fill = "Microsite")+ stat_summary(fun.y=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE)#Boxplot light intensity by microsite

ggplot(shelter.shrub.open, aes((day), temp, color=microsite)) + geom_smooth()+ xlab("Day") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))

ggplot(shelter.shrub.open, aes((day), intensity, color=microsite)) + geom_smooth() + xlab("Day") + ylab ("Solar Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))

#visualizing mean, median, and mode with histograms
ggplot(shelter.shrub.open, aes(temp, fill = microsite)) +
         geom_histogram(binwidth = 5) +
  scale_fill_brewer(palette = "Set1")+   labs(fill = "", x = "Temperature (°F)", y = "Frequency")+theme_classic()+ theme(axis.text=element_text(size=12))+labs(fill = "Microsite")

library(ggpubr)
ggplot(shelter.shrub.open, aes(temp, fill = microsite)) +
         geom_histogram(binwidth = 5) +
  scale_fill_brewer(palette = "Set1")+   labs(fill = "", x = "Temperature (°F)", y = "Frequency")+theme_classic()+ theme(axis.text=element_text(size=12))+ stat_central_tendency(aes(color = microsite), type = "mean", color="green", linetype = 2)+ stat_central_tendency(type = "median", color = "blue", linetype = 2)+ facet_grid(~microsite)+theme(legend.position = "none")

ggplot(shelter.shrub.open, aes(temp, fill = microsite)) +
         geom_density() +
  scale_fill_brewer(palette = "Set1")+   labs(fill = "", x = "Temperature (°F)", y = "Frequency")+theme_classic()+ theme(axis.text=element_text(size=12))+labs(fill = "Microsite")

ggplot(shelter.shrub.open, aes(temp, fill = microsite)) +
         geom_density() +
  scale_fill_brewer(palette = "Set1")+   labs(fill = "", x = "Temperature (°F)", y = "Frequency")+theme_classic()+ theme(axis.text=element_text(size=12))+ stat_central_tendency(aes(color = microsite), type = "mean", color="green", linetype = 2)+ stat_central_tendency(type = "median", color = "blue", linetype = 2)+ facet_grid(~microsite)+theme(legend.position = "none")

``` 


```{r}
#EDA
#explore normality 
#can't do Shapiro-Wilk dataset too large 
library(ggpubr)

ggqqplot(shelter.shrub.open$temp)#Data are positively(right) skewed, Gaussian  
hist(shelter.shrub.open$temp) 
ggqqplot(shelter.shrub.open$intensity)#Data follow a poisson distribution
hist(shelter.shrub.open$intensity)
#Neither intensity nor temperature follow a normal distribution
```
```{r}
#explore light and temperature relationship
macro.micro.contrast <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/micro-macro-contrast.csv")

cor.test(macro.micro.contrast$temp, macro.micro.contrast$intensity, method = "kendall")#light and temperature are correlated p<0.0001, tau=0.2813

#scatterplot for the relationship
ggplot(macro.micro.contrast, aes(temp, intensity))+ geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+theme_classic()#Perhaps too dense too look at

ggplot(macro.micro.contrast, aes(temp, intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  facet_grid(~microsite)+ theme_classic()#faceted by microsite

ggplot(macro.micro.contrast, aes(temp, intensity))+geom_point()+ ylab("Light Intensity (lum/ft²)")+ xlab("Temperature (°F)")+geom_smooth(method='glm', se=FALSE)+  facet_grid(~cover.type)+ theme_classic()#faceted by cover type

```



```{r}
#MODELS
##model hypotheses
##pair-wise comparison
library(sjPlot)
lm.temp <- glm(temp~as.factor(microsite), data = shelter.shrub.open, family="gaussian")
summary (lm.temp)
tab_model(lm.temp)
library (emmeans)
anova(lm.temp, test = "Chisq")
emmeans1 <- emmeans(lm.temp, pairwise~microsite)

lm.intensity <- glm(intensity~as.factor(microsite), data=shelter.shrub.open, family = "quasipoisson")
summary (lm.intensity)
tab_model(lm.intensity)
anova(lm.intensity, test = "Chisq")
emmeans(lm.temp, pairwise~microsite)
emmeans (lm.intensity, pairwise~microsite)

#let's look at shape and blockage intensity more closely
lm.intensity.cover <- glm(intensity~as.factor(microsite)* as.factor(cover.type), data = shelter.shrub.open, family="quasipoisson")
summary(lm.intensity.cover) 
anova (lm.intensity.cover, test="Chisq")#all variables are significant
emmeans(lm.intensity.cover, pairwise~microsite|cover.type)# square-triangle different at 15% and 90%


lm.temp.cover <- glm(temp~as.factor(microsite)* as.factor(cover.type), data = shelter.shrub.open, family="gaussian")
summary(lm.temp.cover) 
anova (lm.temp.cover, test="Chisq")#all variables are significant
emmeans(lm.temp.cover, pairwise~microsite|cover.type)# square-triangle different at 15% and 90%

```
```{r}
#calculating Relative Interaction Index (RII)

#turn table into wide format
data.wide.temp <- reshape (shelter.shrub.open, timevar = "microsite", v.names = "temp", direction = "wide", idvar="date")

data.wide.intensity<- reshape(shelter.shrub.open, timevar = "microsite", v.names = "intensity", direction= "wide", idvar = "date")

#rii for all temperature data
rii.temp.shrub<- data.wide.temp %>%
  mutate(rii_calc_shrub = (temp.shrub.ambient-temp.open)/(temp.shrub.ambient + temp.open))

rii.temp.triangle<- data.wide.temp %>%
  mutate(rii_calc_triangle = (temp.triangle-temp.open)/(temp.triangle + temp.open)) 

rii.temp.square<- data.wide.temp %>%
  mutate(rii_calc_square = (temp.square-temp.open)/(temp.square+ temp.open)) 

#rii for all intensity data
rii.intensity.shrub<- data.wide.intensity %>%
  mutate(rii_calc_shrub = (intensity.shrub.ambient-intensity.open)/(intensity.shrub.ambient+ intensity.open)) #it doesn't work as well as temperature

x <- select(rii.temp.shrub, rii_calc_shrub)
y <- select(rii.temp.triangle, rii_calc_triangle)
z <- select(rii.temp.square, rii_calc_square)
rii.final.temp<-cbind(x, y, z)

rii.csv <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/RII.microsite.csv")

ggplot(rii.csv, aes(Microsite, rii)) +
  geom_boxplot()+ ylab("Relative Interaction Index (RII)")+ geom_hline(yintercept=0, linetype="dashed", color = "red")+ theme_classic()

ggplot(rii.csv, aes(rii, fill = Microsite)) +
  geom_histogram() +
  geom_vline(xintercept = 0, col = 2, lty = 2) +
  labs(x = "Relative Interaction Index (RII)", y = "Frequency", fill = "") +
  scale_fill_brewer(palette = "Paired")+ theme_classic()
```



```{r}
ggplot (shelter.shrub.open, aes(as.factor(day), temp)) + geom_boxplot() + xlab("Day") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))+facet_grid("microsite")+ stat_summary(fun.y=mean, colour="red", geom="point", shape=18, size=1,show_guide = FALSE)

ggplot (shelter.shrub.open, aes(as.factor(day), intensity)) + geom_boxplot() + xlab("Day") + ylab ("Solar Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+ theme(axis.text=element_text(size=12))+facet_grid("microsite")+ stat_summary(fun.y=mean, colour="red", geom="point", shape=18, size=1,show_guide = FALSE)

#let's create a heatmap
ggplot(shelter.shrub.open, aes(as.factor(day), as.factor(microsite), fill=temp))+ geom_tile()+ xlab("Day") + ylab ("Microsite")+theme(axis.text.x = element_text(angle = 90))+ scale_fill_distiller (palette='Blues')+ theme_classic()+ labs(fill = "Temperature (°F)")

#geom_jitter plot for max and min of intensity for each microsite
ggplot(shelter.shrub.open, aes(x = as.factor(microsite), y = intensity)) +
  scale_y_log10() +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4) +
  stat_summary(fun.y = min, colour = "blue", geom = "point", size = 5) +
  stat_summary(fun.y = max, colour = "red", geom = "point", size = 5)+ xlab("")+ ylab("Solar Radiation (lum/ft²)")+theme_classic()

#faceted by microsite
ggplot(shelter.shrub.open, aes(x = as.factor(day), y = intensity)) +
  scale_y_log10() +
  geom_jitter(position = position_jitter(width = 0.1, height = 0), alpha = 1/4) +
  stat_summary(fun.y = min, colour = "blue", geom = "point", size = 5) +
  stat_summary(fun.y = max, colour = "red", geom = "point", size = 5)+ xlab("Day")+ ylab("Light Intensity (lum/ft²)")+theme_classic()+ facet_grid(~microsite)+ coord_flip()+ theme(axis.text.x = element_text(angle = 90))
```



```{r}
#MACRO-MICRO CLIMATE CONTRAST
##test between macro-climate and micro-climate


library (ggplot2)
library(sjPlot)
ggplot(macro.micro.contrast, aes((microsite), temp, fill=microsite)) + geom_boxplot() + xlab("Site") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))+theme(axis.text.x = element_text(angle = 90))+ theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ labs(fill = "Site")+ stat_summary(fun.y=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE)
#weather station data are significantly differnt from shrub, open, and square.

lm.site <- glm(temp~as.factor(microsite), data = macro.micro.contrast, family="gaussian")
summary (lm.site)
tab_model(lm.site)
library (emmeans)
anova(lm.site, test = "Chisq")
emmeans(lm.site, pairwise~microsite)

```

```{r}
#Create microsite map for appendix
library(ggmap)
register_google(key="AIzaSyBpfKtYrkYVS3LEJSjV1cIHeYrxJPsPX4U")
panoche <- get_map(location = c(lon = -120.7932, lat = 36.69363), zoom = 16, maptype = "satellite")
lat_long <- read.csv("C:/Users/Nargol Ghazian/Desktop/Animal-Behaviour-and-Climate-project/CH3/Shrub_Shelter_Open lat long.csv")
na.omit(lat_long)

ggmap(panoche) +
  geom_point(data= lat_long, aes(x=Long, y=Lat, color = Microsite), alpha = 6/10, size =2, show.legend = TRUE) +
  labs(title = "Map of Shelters and Shrubs", x = "Longitude", y = "Latitude")
#Very general arial view of microsites

```


```{r}
#CONCLUSIONS

##1.Temperature and sunlight intensity are correlated.
##2.Shelters function similar to shrubs when lowering temperature and light.
##3.Triangle at 90% is best at loweting both parameters.
##4.The open experienced the most variation. 
##5.Weather station data were different square, shrub, and the open. 

```
