---
title: "CH3-shelter comparison"
author: "Nargol Ghazian"
date: "15/10/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#import dataset 
main.data <- read.csv("C:/Users/Nargol/Desktop/Animal-Behaviour-and-Climate-project/CH3/shelter_logger_comparison.csv")

#open packages 
library (dplyr)
library (ggplot2)
library(ggthemes)

#cleanup data 
#exclude missing values
data.final <-na.omit (main.data)
#check for missing values
is.na(data.final)

summary (data.final)
```


```{r}
#Data visualization 
#automatic data 
qplot (data=data.final, temp)#data seem right-skewed
qplot (data=data.final, Intensity)#data looks exponential, but we have to explore more

#graph a boxplot for temperature, and light per type of cover and shape
ggplot(data.final, aes(as.factor(cover.type), temp, fill= shape)) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))

#boxplots overalp, prehaps significanlty different

ggplot(data.final, aes(as.factor(shelter.open), temp, fill= cover.type)) + geom_boxplot() + xlab("Treatment") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))#don't understand why there is two treatments of shelter and open, gradient looks odd

ggplot(data.final, aes(as.factor(shelter.open), Intensity, fill= cover.type)) + geom_boxplot() + xlab("Treatment") + ylab ("Temperature (°F)")+ theme_classic()+ theme(axis.text=element_text(size=12))

ggplot(data.final, aes(as.factor(cover.type), Intensity, fill= shape)) + geom_boxplot() + xlab("Cover Type (% light permeability)") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))


#let's see if temperature and light intensity are correlated 
qplot(data= data.final, temp, Intensity, geom = c ("point", "smooth")) + xlab("Temperature (°F)") + ylab ("Light Intensity (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))  #there seems to be a positive correlation

#let's see if mean daily temperature varies through time
ggplot(data=data.final, aes(date, temp)) + geom_boxplot(aes(fill=shelter.open))#temperature varies quite a bit during sampling period, again two replicates of treatment are present....



```


```{r}
#EDA
#explore normality 
#can't do Shapiro-Wilk dataset too large 
library(ggpubr)

ggqqplot(data.final$temp)#data is positively(right) skewed 
hist(data.final$temp) 
ggqqplot(data.final$Intensity)
hist(data.final$Intensity)
#neither intensity nor temperature follow a normal distribution
```


```{r}
#Models
cor.test(data.final$temp, data.final$Intensity, method= "kendall")
library (ggpubr)

ggscatter(data.final, x="temp", y="Intensity", add= "reg.line", conf.int = TRUE, cor.coef = TRUE, method="kendall", xlab = "Temperature (°F)", ylab = "Light Intensity (lum/ft²)")#temperature and light are positively correlated (p-value<0.05)

#explore temperature more 
#perform a two-way anova
res.aov2 <- aov(temp~cover.type*shape, data = data.final)
summary (res.aov2)
#no signficant difference between shapes when it comes to temperature, but there is a difference in type of cover when it comes to temperature (p=0.00137<0.01)

#run a non-parametric post-hoc to make sure above is true
kruskal.test(temp ~ cover.type, data = data.final)# p-value<0.05

pairwise.wilcox.test(data.final$temp, data.final$cover.type)
#there is a sig. difference between 50% and 15% (p=0.0013), and between 90% and 50% (p=0.0115)

res.aov3 <- aov(temp~shelter.open*cover.type, data = data.final)
summary (res.aov3)
#significant for shelter versus open with cover as a covariate (p=0.00348<0.01)

#explore light intensity 
res.aov5 <- aov(Intensity~cover.type*shape, data = data.final)
summary (res.aov5)
#the type of cover does not affect light intensity significanly, but just shape and shape and cover together do

glm1 <- glm(temp~shelter.open*cover.type, data = data.final)
summary (glm1)

glm2 <- glm(temp~shelter.open*shape, data = data.final)
summary (glm2)

glm3 <- glm (Intensity~cover.type*shape, data = data.final)
summary (glm3)

```

```{r}
#Summary 
###1. The intensity of sunlight and temperature are positively correlated.(R=0.61, p-value= <2.2e-16)
###2. Shape does not significanly affect the temperature of canopy.
###3. The percentage of cover used significantly affects temperature (p-value=0.00137<0.01).
###3. there is a signicant difference between 50% and 15% cover (p-value=0.0013), and between 90% and 50% (p-value=0.0115), cover when it comes to temperature.
###4. The type of cover used does not affect sunlight under canopy significantly by itself, however shape and shape and type of cover together do have a sginificant impact (p-value=0.0115<0.05, and p-value=<2e-16<0001, respectively)
```






```{r}